<?php
/*** Textos base ***/
$array_textos = array(
	'Aviso legal' => array(
		'es' => '	<p>En cumplimiento de la Ley 34/2002, de 11 de julio, de servicios de la sociedad de la información y de comercio electrónico, %cliente_fiscal% le informa de que es titular del website %cliente_web%. De acuerdo con la exigencia del artículo 10 de la citada Ley, %cliente_fiscal% informa de los siguientes datos: El titular de esta página web es %cliente_fiscal%, con NIF %cliente_nif%, %registro_mercantil%con inscripción en el Registro Mercantil de %cliente_rm_ubicacion%, %cliente_rm_inscripcion%,%/registro_mercantil% y domicilio social en %cliente_direccion_1%, %cliente_direccion_2%. La dirección de correo electrónico de contacto con la empresa es %cliente_correo%.</p>
					<h3>USUARIO Y RÉGIMEN DE RESPONSABILIDADES</h3>
					<p>La navegación, acceso y uso por el website de %cliente_fiscal% confiere la condición de usuario, por la que se aceptan, desde la navegación por las páginas de %cliente_fiscal%, todas las condiciones de uso aquí establecidas sin perjuicio de la aplicación de la correspondiente normativa de obligado cumplimiento legal según el caso.</p><p> Las páginas web de %cliente_fiscal% proporcionan gran diversidad de información, servicios y datos. El usuario asume su responsabilidad en el uso correcto del website. Esta responsablidad se extenderá a:</p><ul><li>La veracidad y licitud de las informaciones aportadas por el usuario en los formularios extendidos por %cliente_fiscal% para el acceso a ciertos contenidos o servicios ofrecidos por las webs. También será responsable del uso que le de a las claves de acceso que haya obtenido con la cumplimentación de los formularios mencionados.</li><li>El uso de la información, servicios y datos ofrecidos por %cliente_fiscal% contrariamente a lo dispuesto por las presentes condiciones, la Ley, la moral, las buenas costumbres o el orden público, o que de cualquier otro modo puedan suponer lesión de los derechos de terceros o del mismo funcionamiento del website.</li></ul></p>
					<h3>POLÍTICA DE ENLACES Y EXENCIONES DE RESPONSABILIDAD</h3>
					<p>%cliente_fiscal% no se hace responsable del contenido de las páginas web a las que el usuario pueda acceder a través de los enlaces establecidos en su website y declara que en ningún caso procederá a examinar o ejercitar ningún tipo de control sobre el contenido de otras páginas de la red.</p><p>Asimismo, tampoco garantizará la disponibilidad técnica, exactitud, veracidad, validez o legalidad de páginas ajenas a su propiedad a las que se pueda acceder por medio de los enlaces.</p><p>%cliente_fiscal% declara haber adoptado todas las medidas necesarias para evitar cualesquiera daños que, a los usuarios de su website, pudieran derivarse de la navegación por sus páginas web. En consecuencia, %cliente_fiscal% no se hace responsable, en ningún caso, de los eventuales daños que por la navegación por Internet pudiera sufrir el usuario.</p>
					<h3>MODIFICACIONES</h3>
					<p>%cliente_fiscal% se reserva el derecho a realizar las modificaciones que considere oportunas, sin aviso previo, en el contenido de su website. Tanto en lo referente a los contenidos de la website, como en las condiciones de uso de la misma o en las condiciones generales de contratación. Dichas modificaciones podrán realizarse, a través de su website, de cualquier forma admisible en derecho y serán de obligado cumplimiento durante el tiempo en que se encuentren publicadas en la web y hasta que no sean modificadas válidamente por otras posteriores.</p>
					<h3>PROPIEDAD INTELECTUAL</h3>
					<p>Los derechos de propiedad intelectual e industrial derivados de todos los textos, imágenes, así como de los medios y formas de presentación y montaje de sus páginas pertenecen, por sí o como cesionaria, a %cliente_fiscal% Serán, por consiguiente, obras protegidas como propiedad intelectual por el ordenamiento jurídico español, siéndoles aplicables tanto la normativa española y comunitaria en este campo, como los tratados internacionales relativos a la materia y suscritos por España.</p><p>Todos los derechos reservados. En cumplimiento de la Ley de la Propiedad Intelectual se prohíbe expresamente la reproducción, distribución, comunicación pública y utilización, de la totalidad o parte de los contenidos de sus páginas web sin el consentimiento expreso de %cliente_fiscal%.</p>
					<h3>ACCIONES LEGALES, LEGISLACIÓN APLICABLE Y JURISDICCIÓN</h3>
					<p>%cliente_fiscal% se reserva asimismo la facultad de presentar las acciones civiles o penales que considere oportunas por la utilización indebida de sus páginas web y contenidos o por el incumplimiento de las presentes condiciones.</p><p>La relación entre el usuario y %cliente_fiscal% se regirá por la normativa española vigente y serán competentes para decidir sobre cualquier controversia que se pudiera suscitar entre el usuario y %cliente_fiscal%, los juzgados o tribunales propios de la localidad de %cliente_direccion_2%.</p>',
		'eu' => '	<p>Gizarteko zerbitzuei eta merkataritza elektronikoari buruzko uztailaren 11ko 34/2002 Legea betez, %cliente_web% web gunearen titularra dela jakinarazten du %cliente_fiscal%(e)k. Aipatu Legearen 10. artikuluak jasotzen duenari jarraikiz, honako datu hauen berri ematen du %cliente_fiscal%(e)k: Web orri honen titularra %cliente_fiscal% da, %cliente_nif% IFZ duena, %registro_mercantil%"Registro Mercantil de %cliente_rm_ubicacion%"-n "%cliente_rm_inscripcion%" duena,%/registro_mercantil% eta %cliente_direccion_1%, %cliente_direccion_2% helbide soziala duena. Enpresaren harremanetarako posta elektronikoko helbidea %cliente_correo% da.</p>
					<h3>ERABILTZAILEA ETA ERANTZUKIZUNEN ERREGIMENA</h3>
					<p>%cliente_fiscal%(e)ren web gunean barrena nabigatzen, bertara sartzen eta erabiltzen duena erabiltzaile bilakatzen da eta, horrenbestez, %cliente_fiscal%(e)ren orrietan nabigatzetik hasita, hemen ezarritako erabilera-baldintza guztiak onartzen ditu, kasuak kasu, legez halabeharrez bete beharreko araudia aplikatzeari kalterik egin gabe.</p><p> %cliente_fiscal%(e)ren web orriek informazio, zerbitzu eta datu ugari eskaintzen dituzte. Erabiltzaileak web gunea behar bezala erabiltzeko erantzukizuna hartzen du bere gain. Aipatu erantzukizunak honako hauek ere barne hartzen ditu:</p><ul><li>Web orriek eskainitako zenbait eduki edo zerbitzu eskuratzeko orduan, %cliente_fiscal%(e)k eskura jartzen dituen formularioetan erabiltzaileak ematen duen informazio oro egiazkoa eta legezkoa izatea. Erantzukizuna izango du, halaber, aipatu formularioak betetzerakoan eskuratutako sarrera-gakoei emandako erabileraren inguruan.</li><li>Bere erantzukizuna izango da %cliente_fiscal%(e)k eskainitako informazioa, zerbitzuak eta datuak aipatu baldintzetan, Legean, moralean, jardunbide egokietan edo ordena publikoan ezarritakoaren aurka erabiltzea, bai eta beste moduren batean hirugarren pertsonen eskubideei edo web gunearen funtzionamenduari kalteak eragitea ere.</li></ul>
					<h3>LOTUREN POLITIKA ETA ERANTZUKIZUNEN SALBUESPENAK</h3>
					<p>%cliente_fiscal%(e)k ez du inolako ardurarik izango bere web gunean jarritako loturen bidez erabiltzailea sar daitekeen bestelako web orrien edukiaren gainean; bestalde, %cliente_fiscal%(e)k adierazten du ez dituela inondik inora sareko beste orri batzuk aztertuko edo horien gaineko kontrolik burutuko.</p><p>Era berean, ez ditu loturen bidez eskura daitezkeen baina berari ez dagozkion orrien gaineko erabilgarritasun teknikoa, zehaztasuna, egiazkotasuna, baliozkotasuna edo legaltasuna bermatuko.</p><p>%cliente_fiscal%(e)k adierazten du bere web orrietan barrena nabigatzearen ondorioz bere web guneko erabiltzaileei sor dakizkiekeen edonolako kalteak saihesteko beharrezko neurri guztiak hartu dituela. Ondorioz, %cliente_fiscal%(e)k ez du inondik inora erabiltzaileak Interneten barrena nabigatzearen ondorioz jasan ditzakeen balizko kalteen gaineko erantzukizunik izango.</p>
					<h3>ALDAKETAK</h3>
					<p>%cliente_fiscal%(e)k bere web gunearen edukian egoki deritzon aldaketak egiteko eskubidea du, aldez aurretik jakinarazi gabe. Bai web gunearen edukiei dagokienez, bai web gunea erabiltzeko baldintzei edo kontratazioaren baldintza orokorrei dagokienez. Aldaketa horiek bere web gunearen bidez egin ahal izango dira zuzenbidean onartzen den edozein modutan, eta halabeharrez bete beharko dira web orrian argitaratuta dauden bitartean eta beste batzuen ordez baliozki aldatzen ez diren artean.</p>
					<h3>JABETZA INTELEKTUALA</h3>
					<p>Web orrietako testu, irudi zein aurkezpen eta muntaiak egiteko baliabide eta modu guztien ondoriozko jabetza intelektual eta industrialaren eskubideak %cliente_fiscal%(e)ri dagozkio, berez edo lagapen-hartzaile gisa. Horrenbestez, Espainiako ordenamendu juridikoak jabetza intelektual gisa babestutako obrak izango dira eta alor honetako araudi espainiarra eta komunitateari dagokiona aplikatuko zaie, bai eta gai honi buruzko nazioarteko itunak eta Espainiak sinatutakoak ere.</p><p>Eskubide guztiak erreserbatuta daude. Jabetza Intelektualaren Legea betez, espresuki debekatuta dago web orrien eduki guztia edo edukien zati bat %cliente_fiscal%(e)ren berariazko baimenik gabe kopiatzea, banatzea, jendaurrean jakinaraztea eta erabiltzea.</p>
					<h3>AKZIO LEGALAK, LEGERIA APLIKAGARRIA ETA JURISDIKZIOA</h3>
					<p>%cliente_fiscal%(e)k, halaber, bere orriak eta edukiak oker erabiltzeagatik edo aipatu baldintzak ez betetzeagatik egoki deritzon akzio zibilak edo penalak aurkezteko eskumena du.</p><p>Erabiltzailearen eta %cliente_fiscal%(e)ren arteko harremana indarreko araudi espainiarraren arabera arautuko da, eta erabiltzailearen eta %cliente_fiscal%(e)ren artean sor daitekeen edozein eztabaida ebazteko eskumena %cliente_direccion_2% udalerriko epaitegi edo auzitegiek izango dute.</p>',
		'en' => '	<p>In compliance with Law 34/2002 of July 11 for information society and electronic commerce services, %cliente_fiscal% informs that it is the owner of the %cliente_web% website. In accordance with that stated in Article 10 of the above mentioned law, %cliente_fiscal% informs of the following data: The owner of the website is %cliente_fiscal%, with VAT %cliente_nif%, %registro_mercantil%with "%cliente_rm_inscripcion%" at "Registro Mercantil de %cliente_rm_ubicacion%",%/registro_mercantil% and located at %cliente_direccion_1%, %cliente_direccion_2%. The e-mail address to contact the company is %cliente_correo%.</p>
					<h3>USER AND SYSTEM OF RESPONSIBILITIES</h3>
					<p>The navigation, access and use of the %cliente_fiscal% website confers the user status by accepting all the conditions of use, as they are accepted from the moment of navigation on the %cliente_fiscal% website all conditions of use set forth herein without prejudice to the application of the corresponding binding legal regulations as appropriate.</p><p>The %cliente_fiscal% website provides a wide range of information, services and data The user assumes responsibility for the proper use of the website. This responsibility extends to:</p><ul><li>The accuracy and legality of the information provided by the user in the forms issued by %cliente_fiscal% for access to certain content or services offered by the websites. The user will also be responsible for any use related to the passwords obtained with the completion of the mentioned forms.</li><li>The use of the information, services and data offered by %cliente_fiscal% contrary to the provisions of these terms, the Law, moral codes, norms of good behaviour, public order or any other means that may involve injury to the rights of others or the operation of the website.</li></ul>
					<h3>POLICY ON LINKS AND DISCLAIMERS</h3>
					<p>%cliente_fiscal% is not responsible for content on third party websites accessed by the user through the links provided on its website and states that under no circumstances will it proceed to review or exercise any control over the content of the other sites on the web.</p><p>Nor does it guarantee the technical availability, accuracy, reliability, validity or legality of websites outside its control and ownership that may be accessed through links.</p><p>%cliente_fiscal% declares that it has adopted all the measures required to prevent any damages to web users that may be derived from navigating the site. Consequently, %cliente_fiscal% is not responsible in any way of possible damages that Internet surfing may cause the user.</p>
					<h3>MODIFICATIONS</h3>
					<p>%cliente_fiscal% reserves the right to make any changes it may consider necessary, without prior notice, to the contents of its website. Both in regards to site contents, as well as conditions of use and the general conditions of contracting of the same. Said modifications may be made through its website in any way admissible under law and will be binding for as long as they are published on the web and until they are subsequently validly amended.</p>
					<h3>INTELLECTUAL PROPERTY</h3>
					<p>The rights of intellectual property derived from all texts and images, as well as the manner and means of presentation and assembly within its pages belong to, as the assignee, %cliente_fiscal% and will therefore be considered intellectual property by the Spanish legal system with both Spanish and Community law being applicable together with any international treaties relating to the subject and undersigned by Spain.</p><p>All rights reserved. In compliance with the Law of Intellectual Property, the reproduction, distribution, public communication and use of all or part of the content of its websites is expressly prohibited without the express consent of %cliente_fiscal%.</p>
					<h3>LEGAL ACTIONS, APPLICABLE LEGISLATION AND JURISDICTION</h3>
					<p>%cliente_fiscal% also reserves the right to file civil or criminal actions as it deems appropriate for the misuse of its websites and content, or for breach of the above stated conditions.</p><p>The relationship between the user and %cliente_fiscal% shall be governed by Spanish legislation, and will be competent to decide any dispute that might arise between the user and %cliente_fiscal%, the courts or tribunals in the locality of %cliente_direccion_2%.</p>',
		'fr' => '	<p>Conformément à la loi 34/2002, du 11 juillet, sur les services de la société de l\'information et du commerce électronique, %cliente_fiscal% vous informe qu\'il est titulaire du site web %cliente_web%. Selon les dispositions de l\'article 10 de cette loi, %cliente_fiscal% informe des éléments suivants: Le titulaire de ce site est %cliente_fiscal%, dont le FNI est %cliente_nif%, %registro_mercantil%dont le "Registro Mercantil de %cliente_rm_ubicacion%" est "%cliente_rm_inscripcion%",%/registro_mercantil% et dont le siège social est %cliente_direccion_1%, %cliente_direccion_2%. L\'adresse électronique de contact de l\'entreprise est %cliente_correo%.</p>
					<h3>UTILISATEUR ET RÉGIME DE RESPONSABILITÉS</h3>
					<p>La navigation, l\'accès et l\'utilisation du site web %cliente_fiscal% confère la condition d\'utilisateur et entra&icirc;nent l\'acceptation, à partir de la navigation des pages de %cliente_fiscal%, de toutes les conditions d\'utilisation établies dans le présent document sans préjudice de l\'application de la législation correspondante obligatoire selon le cas.</p><p>Les pages web de %cliente_fiscal% offrent une grande diversité d\'informations, de services et de données. Il est de la responsabilité de l\'utilisateur de faire bon usage du site web. Cette responsabilité s\'étendra à:</p><ul><li>la véracité et légalité des informations apportées par l\'utilisateur dans les formulaires présentés par %cliente_fiscal% pour l\'accès à certains contenus ou services offerts par les webs. L\'utilisateur sera également responsable de l\'utilisation des codes d\'accès qu\'il aura obtenus en remplissant les formulaires susmentionnés.</li><li>Une utilisation des informations, services et données offerts par %cliente_fiscal% contraire à ce qui appara&icirc;t dans les conditions présentes, à la loi, à la morale, aux bonnes manières ou à l\'ordre public pourrait supposer un préjudice des droits de tiers ou du fonctionnement m&ecirc;me du site web.</li></ul>
					<h3>POLITIQUE DE LIENS ET EXEMPTIONS DE RESPONSABILITÉ</h3>
					<p>%cliente_fiscal% ne sera pas responsable du contenu des pages web auxquelles l\'utilisateur pourra accéder par le biais des liens établis sur son site web et il déclare qu\'en aucun cas il ne procèdera à examiner ou exercer aucun type de contr&ocirc;le sur le contenu d\'autres pages du réseau.</p><p>Il ne garantira pas non plus la disponibilité technique, l\'exactitude, la véracité, la validité ou la légalité de pages étrangères à sa propriété auxquelles on pourrait accéder par les liens.</p><p>%cliente_fiscal% déclare avoir adopté toutes les mesures nécessaires pour éviter tous les préjudices que la navigation sur ses pages web pourrait provoquer chez les utilisateurs. Par conséquent, %cliente_fiscal% ne sera en aucun cas responsable des éventuels préjudices que l\'utilisateur pourrait subir en naviguant sur Internet.</p>
					<h3>MODIFICATIONS</h3>
					<p>%cliente_fiscal% se réserve le droit de réaliser les modifications du contenu de son site web qu\'il considère pertinentes, sans avis préalable, aussi bien en ce qui concerne les contenus du site web que des conditions d\'utilisation de celui-ci ou des conditions générales de souscription. Ces modifications pourront &ecirc;tre réalisées par le site web de n\'importe quelle forme légalement acceptable et leur respect sera obligatoire pendant toute la durée de leur publication sur le site et jusqu\'à ce qu\'elles soient modifiées.</p>
					<h3>PROPRIÉTÉ INTELLECTUELLE</h3>
					<p>Les droits de propriété intellectuelle et industrielle dérivés de tous les textes, les images ainsi que les moyens et formes de présentation et montage de ses pages appartiennent, en tant que telles ou comme cessionnaire, à %cliente_fiscal%. Ils seront par conséquent considérés comme des &oelig;uvres de propriété intellectuelle par l\'ordonnancement juridique espagnol et ils seront régis par la législation espagnole et communautaire dans ce domaine, ainsi que par les traités internationaux souscrits par l\'Espagne.</p><p>Tous droits réservés. Conformément à la loi de propriété intellectuelle, la reproduction, distribution, communication publique et utilisation de la totalité ou d\'une partie des contenus de ses pages web sont formellement interdites sans le consentement de %cliente_fiscal%.</p>
					<h3>ACTIONS LÉGALES, LÉGISLATION APPLICABLE ET JURIDICTION</h3>
					<p>%cliente_fiscal% se réserve la faculté de présenter les actions civiles ou pénales qu\'il considère opportunes en cas d\'utilisation illicite de ses pages web et contenus ou de non-respect des présentes conditions.</p><p>La relation entre l\'utilisateur et %cliente_fiscal% sera régie par la législation espagnole en vigueur et les tribunaux de la localité de %cliente_direccion_2% seront compétents pour statuer en cas de litige ou controverse entre l\'utilisateur et %cliente_fiscal%.</p>',
		'de' => '	<p>In Übereinstimmung mit dem Gesetz 34/2002 vom 11. Juli über E-Commerce und die Dienste der Informationsgesellschaft, informiert Sie %cliente_fiscal%, dass es der Eigentümer der Website %cliente_web% ist. In Übereinstimmung mit den Anforderungen des Artikels 10 des genannten Gesetzes, informiert Sie %cliente_fiscal% über folgende Daten: %cliente_fiscal%, mit der Steuernummer %cliente_nif% und Sitz im %cliente_direccion_1%, %cliente_direccion_2% ist der Inhaber und Betreiber dieser Webseite. Die Kontakt-E-Mail-Adresse des Unternehmens ist: %cliente_correo%.</p>
					<h3>BENUTZER UND HAFTUNGSREGELUNG</h3>
					<p>Surfen, Zugang und Nutzung der Webseite %cliente_fiscal% verleiht Ihnen den Status des Benutzers, was wiederum bedeutet, dass Sie im Moment des Zugriffs auf die Webseite ausdrücklich und ohne Vorbehalte allen hierin festgelegten Nutzungsbedingungen zustimmen, unbeschadet der Anwendung der entsprechenden Rechtsvorschriften.</p><p>Die Webseiten von %cliente_fiscal% bieten eine Vielzahl an Informationen, Serviceleistungen und Daten. Der Benutzer übernimmt die Verantwortung für die ordnungsgemäße Nutzung der Webseite. Diese Verantwortung umfasst:</p><ul><li>Die Richtigkeit und Rechtmäßigkeit der vom Benutzer in den Formularen von %cliente_fiscal% übermittelten Informationen für den Zugang zu bestimmten Inhalten oder den von Webseiten angebotenen Diensten. Der Benutzer ist auch verantwortlich für die ordnungsgemäße Nutzung der Passwörter, die er durch Ausfüllen der angeführten Formulare erhalten hat.</li><li>Die Verwendung von Informationen, Dienstleistungen und Daten von %cliente_fiscal%, die im Widerspruch zu diesen Geschäftsbedingungen, dem Gesetz, der Moral, den guten Sitten oder der öffentlichen Ordnung stehen oder welche in irgendeiner Weise eine Verletzung der Rechte Dritter darstellen oder die Funktionalität der Webseiten einschränken können.</li></ul>
					<h3>LINKS UND HAFTUNGSAUSSCHLUSS</h3>
					<p>%cliente_fiscal% übernimmt keinerlei Haftung für den Inhalt von Webseiten, auf die der Benutzer über Links auf seiner Website zugreift und betont, dass das Unternehmen keine Kontrolle oder Überprüfung der Inhalte anderer Webseiten im Netz ausüben wird.</p><p>Gleichermaßen lehnt das Unternehmen auch jegliche Garantie für die technische Verfügbarkeit, Genauigkeit, Zuverlässigkeit, Gültigkeit oder Rechtmäßigkeit unternehmensfremder Seiten ab, auf die man über Links zugreifen kann.</p><p>%cliente_fiscal% gibt an, alle notwendigen Maßnahmen getroffen zu haben, um Schäden für die Nutzer seiner Website zu vermeiden, die aufgrund des Surfens derselben entstehen könnten. Folglich lehnt %cliente_fiscal% jegliche Haftung für Schäden ab, die der Benutzer beim Surfen im Internet eventuell erleiden könnte.</p>
					<h3>ÄNDERUNGEN</h3>
					<p>%cliente_fiscal% behält sich das Recht vor, ohne vorherige Ankündigung alle Änderungen im Inhalt seiner Webseite vorzunehmen, die das Unternehmen für angemessen hält. Dies gilt sowohl in Bezug auf den Inhalt der Webseite als auch ihre Nutzungsbedingungen oder die allgemeinen Geschäftsbedingungen. Diese Änderungen können über seine Webseite in jeder rechtlich zulässigen Weise durchgeführt werden und sind bindend einzuhalten für den Zeitraum, in dem sie im Netz veröffentlich sind und solange, bis sie nicht wirksam durch nachfolgende Änderungen modifiziert werden.</p>
					<h3>URHEBERRECHT</h3>
					<p>Alle aus Texten, Bildern, sowie Darstellungsformen und Mitteln seiner Seiten abgeleiteten Rechte an geistigem Eigentum und gewerblichen Schutzrechten sind per se oder als Zessionar das Eigentum von %cliente_fiscal%. Von daher sind sie nach spanischem Recht als geistiges Eigentum geschützt, wobei sowohl die entsprechenden spanischen als auch die EU-Vorschriften zutreffen, sowie die diese Angelegenheit betreffenden und von Spanien ratifizierten internationalen Verträge.</p><p>Alle Rechte vorbehalten. In Erfüllung des Gesetzes über geistiges Eigentum ist jede Vervielfältigung, Verbreitung, Veröffentlichung und Wieder,- bzw. Weitergabe der Inhalte seiner Webseiten ohne ausdrückliche Genehmigung seitens %cliente_fiscal% ausdrücklich untersagt.</p>
					<h3>RECHTLICHE SCHRITTE, GELTENDES RECHT UND GERICHTSBARKEIT</h3>
					<p>%cliente_fiscal% behält sich das Recht vor, im Falle von Missbrauch seiner Webseiten und Inhalte oder der Verletzung der vorliegenden Bedingungen zivil- oder strafrechtliche Maßnahmen einzuleiten. </p><p>Die Beziehung zwischen dem Benutzer und %cliente_fiscal% unterliegt der spanischen Gesetzgebung. Im Falle von Unstimmigkeiten zwischen dem Benutzer und %cliente_fiscal% sind die Richter und Gerichte von %cliente_direccion_2% zuständig.</p>',
	),
	'Política de protección de datos' => array(
		'es' => '	<h3>¿Quién es el responsable de sus datos?</h3>
					<p>De acuerdo con lo establecido por el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, le informamos que los datos personales aportados serán tratados por %cliente_fiscal% con NIF %cliente_nif% y domicilio social en %cliente_direccion_1%, %cliente_direccion_2%.</p>
					<h3>¿Con qué finalidad tratamos sus datos personales?</h3>
					<p>Los datos aportados por usted son necesarios para contactar con usted, atender a sus consultas y peticiones y, si decide suscribirse, enviar boletines informativos.</p>
					<h3>¿Por cuánto tiempo conservaremos sus datos?</h3>
					<p>Los datos personales proporcionados se conservarán mientras se prevea que pueden ser necesarios para contactar con el interesado.</p>
					<h3>¿Cuál es la legitimación para el tratamiento de sus datos?</h3>
					<p>La base legal para el tratamiento de sus datos es el consentimiento del interesado al proporcionar sus datos.</p>
					<h3>¿A qué destinatarios se comunicarán sus datos?</h3>
					<p>Sus datos no se cederán a terceros salvo obligación legal.</p>
					<h3>¿Cuáles son sus derechos cuando nos facilita sus datos?</h3>
					<p>Cualquier persona tiene derecho a solicitar el acceso, rectificación, supresión, limitación del tratamiento, oposición o derecho a la portabilidad de sus datos personales, escribiéndonos a nuestra dirección arriba indicada, o enviando un correo electrónico a %cliente_correo_pd%, indicando el derecho que desea ejercer.</p>
					<p>Tendrá derecho igualmente a retirar el consentimiento prestado en cualquier momento. La retirada del consentimiento no afectará a la licitud del tratamiento efectuado antes de la retirada de dicho consentimiento.</p>
					<p>Tiene derecho a presentar una reclamación ante la autoridad de control si considera que pueden haber sido vulnerados sus derechos en lo concerniente a la protección de sus datos personales.</p>',
		'eu' => '	<h3>Nork du zure datuen ardura?</h3>
					<p>Europako Parlamentuaren eta Kontseiluaren (UE) 2016/679 Erregelamenduak ezarritakoaren arabera, jakinarazten dizugu emandako datu pertsonalak %cliente_fiscal%-(e)k, IFK %cliente_nif% duenak, eta helbide soziala %cliente_direccion_1%, %cliente_direccion_2% duenak tratatuko dituela.</p>
					<h3>Zein helburu ditugu zure datu pertsonalak tratatzeko?</h3>
					<p>Zuk emandako datuak beharrezkoak dira zurekin harremanetan jartzeko, zure kontsulta eta eskaerei erantzuteko eta, harpidetzea erabakitzen baduzu, informazio-buletinak bidaltzeko.</p>
					<h3>Zenbat denboraz gordeko ditugu zure datuak?</h3>
					<p>Emandako datuak gordeta edukiko dira, interesdunarekin harremanetan jartzeko beharrezkoak direla aurreikusten den artean.</p>
					<h3>Nola legitimatzen da zure datu-tratamendua?</h3>
					<p>Zure datuen tratamendurako lege-oinarria datza datuak ematean interesdun gisa egiten duzun onarpenean.</p>
					<h3>Zer hartzaileei jakinaraziko zaizkie zure datuak?</h3>
					<p>Zure datuak ez zaizkio ezein hirugarreni lagako, lege-obligazioz izan ezik.</p>
					<h3>Zein eskubide erabil ditzakezu datuak ematearen inguruan?</h3>
					<p>Pertsona orok du bere datu pertsonalak eskuratu, zuzendu, tratamendua mugatu, eta aurkatzeko eskubidea edota datuoneramangarritasunerako eskubidea;eta horiek erabili ahal izateko,goialdean ageri den gure helbidera idatzi beharko da, edo mezu elektroniko bat bidali%cliente_correo_pd% helbidera;bertan adierazita zein eskubide erabili nahi duzun.</p>
					<p>Halaber, emandako adostasuna edonoiz ezezteko eskubidea izango duzu. Adostasunhori kentzeak ez dio eragingo aurretiko datu-tratamenduaren zilegitasunari.</p>
					<p>Zure datu pertsonalen babesari dagozkion eskubideak urratu direla uste izanez gero, eskubidea duzu kontrol-agintaritzari erreklamazioa egiteko.</p>',
		'en' => '	<h3>Who is responsible for your data?</h3>
					<p>Pursuant to provisions in European Parliament and Council (EU) Regulation 2016/679, you are hereby informed that the personal data provided shall be processed by %cliente_fiscal% with Tax ID Number %cliente_nif% and corporate headquarters at %cliente_direccion_1%, %cliente_direccion_2%.</p>
					<h3>Why are we processing your personal data?</h3>
					<p>The data provided by you are necessary for the purposes of contacting you, responding to your queries and requests and, if you choose to sign up for it, to send you newsletters.</p>
					<h3>How long will we store your data?</h3>
					<p>The personal data provided will be kept for as long as is considered necessary for contacting the interested party.</p>
					<h3>What is the legitimisation for processing your data?</h3>
					<p>The lawful basis for processing your data is consent of the interested party on providing their data.</p>
					<h3>To whom will your data be disclosed?</h3>
					<p>Your data will not be disclosed to third parties unless legally compelled to do so.</p>
					<h3>What are your rights when you provide us with your data?</h3>
					<p>Any individual has the right to request access, rectification, deletion, processing limitation, opposition or transfer of his or her personal data, by writing to us at the address provided above or sending an email to %cliente_correo_pd%, stating the right he or she wishes to exercise.</p>
					<p>He or she shall also be entitled to withdraw consent at any time. Withdrawal of consent shall not affect the legality of prior processing before withdrawing said consent.</p>
					<p>He or she is entitled to file a claim with the control authority if he or she deems that his or her rights have been violated, insofar as protection of personal data is concerned.</p>',
		'fr' => '	<h3>Qui est le responsable de vos données?</h3>
					<p>Conformément aux prévisions du Règlement (UE) 2016/679 du Parlement Européen et du Conseil, nous vous informons que les données à caractère personnel fournies seront traitées par %cliente_fiscal%, NIF %cliente_nif% et domicile fiscal à %cliente_direccion_1%, %cliente_direccion_2%.</p>
					<h3>Dans quel but traitons-nous vos données personnelles?</h3>
					<p>Les données que vous nous apportez sont nécessaires pour vous contacter, répondre à vos questions et à vos demandes et, si vous décidez de vous abonner, pour vous envoyer nos bulletins d\'informations.</p>
					<h3>Combien de temps conserverons-nous vos données?</h3>
					<p>Les données personnelles fournies seront conservées pendant toute la durée que nous jugeons nécessaire pour contacter l\'intéressé.</p>
					<h3>Quelle est la légitimation dans le traitement de vos données?</h3>
					<p>Le traitement des données est légalement fondé sur le consentement de l\'intéressé lorsqu\'il fournit ses données.</p>
					<h3>À quels destinataires seront communiquées vos données?</h3>
					<p>Vos données ne seront pas cédées à des tiers, sauf obligation légale.</p>
					<h3>Quels sont vos droits en nous fournissant vos données?</h3>
					<p>Vous êtes en droit de demander l\'accès, la rectification, la suppression, la limitation du traitement, l\'opposition ou le droit à la portabilité de vos données personnelles, en nous écrivant à notre adresse indiquée ci-dessus, ou en nous envoyant un courrier électronique à %cliente_correo_pd%, en indiquant le droit que vous souhaitez exercer.</p>
					<p>Vous aurez également le droit de retirer, à tout moment, le consentement donné. Le retrait du consentement n\'altèrera pas la légalité du traitement effectué avant son retrait.</p>
					<p>Vous avez le droit de présenter une réclamation devant l\'autorité de contrôle si vous considérez que vos droits ont pu être violés en ce qui concerne la protection de vos données à caractère personnel.</p>',
		'de' => '	<h3>Wer ist für Ihre Daten verantwortlich?</h3>
					<p>Gemäß den Bestimmungen der Verordnung (EU) 2016/679 des Europäischen Parlaments und des Rates teilen wir Ihnen mit, dass die angegebenen personenbezogenen Daten von %cliente_fiscal% mit der Steuernummer %cliente_nif% und Geschäftssitz in %cliente_direccion_1%, %cliente_direccion_2% verarbeitet werden. </p>
					<h3>Zu welchem Zweck verarbeiten wir Ihre persönlichen Daten?</h3>
					<p>Die von Ihnen bereitgestellten Daten sind erforderlich, um mit Ihnen Kontakt aufzunehmen, Ihre Fragen und Anfragen zu beantworten und, falls Sie sich für ein Abonnement entscheiden, Ihnen den Newsletter zuzustellen.</p>
					<h3>Wie lange verwahren wir Ihre Daten?</h3>
					<p>Die bereitgestellten personenbezogenen Daten werden solange aufbewahrt, wie davon auszugehen ist, dass sie zur Kontaktaufnahme mit dem Betroffenen erforderlich sind.</p>
					<h3>Welche Berechtigung besteht für die Verarbeitung Ihrer Daten?</h3>
					<p>Die Rechtsgrundlage für die Verarbeitung seiner Daten ist die mit der Bereitstellung dieser Daten gegebene Zustimmung des Betroffenen.</p>
					<h3>An welche Empfänger werden Ihre Daten übermittelt?</h3>
					<p>Ihre Daten werden nur im Falle einer gesetzlichen Verpflichtung an Dritte weitergegeben.</p>
					<h3>Welche Rechte haben Sie, wenn Sie uns Ihre Daten zur Verfügung stellen?</h3>
					<p>Sie können Ihr Recht auf Zugang, Berichtigung, Löschung, Einschränkung der Verarbeitung, Widerspruch oder Übertragbarkeit Ihrer persönlichen Daten mittels Schreiben an unsere oben genannte Adresse oder per E-Mail an %cliente_correo_pd% unter Angabe des gewünschten Rechts geltend machen.</p>
					<p>Sie haben zudem das Recht, die erteilte Einwilligung jederzeit zu widerrufen. Der Widerruf der Einwilligung hat keinen Einfluss auf die Rechtmäßigkeit der vor dem Widerruf dieser Zustimmung durchgeführten Verarbeitung.</p>
					<p>Sie haben das Recht, bei der Aufsichtsbehörde einen Antrag zu stellen, wenn Sie der Meinung sind, dass Ihre Rechte zum Schutz Ihrer persönlichen Daten verletzt wurden.</p>',
	),
	'Política de cookies' => array(
		'es' => '	<h3>¿Qué es una cookie?</h3>
					<p>Cookie es un fichero que se descarga en su ordenador al acceder a determinadas páginas web. Las cookies permiten a una página web, entre otras cosas, almacenar y recuperar información sobre los hábitos de navegación de un usuario o de su equipo y, dependiendo de la información que contengan y de la forma en que utilice su equipo, pueden utilizarse para reconocer al usuario. El navegador del usuario memoriza cookies en el disco duro solamente durante la sesión actual ocupando un espacio de memoria mínimo y no perjudicando al ordenador. Las cookies no contienen ninguna clase de información personal específica, y la mayoría de las mismas se borran del disco duro al finalizar la sesión de navegador (las denominadas cookies de sesión).</p><p>La mayoría de los navegadores aceptan como estándar a las cookies y, con independencia de las mismas, permiten o impiden en los ajustes de seguridad las cookies temporales o memorizadas.</p>
					<h3>¿Qué tipos de cookies utiliza esta página web?</h3>
					<ul><li>Cookies técnicas: Son aquéllas que permiten al usuario la navegación a través de una página web, plataforma o aplicación y la utilización de las diferentes opciones o servicios que en ella existan como, por ejemplo, controlar el tráfico y la comunicación de datos, identificar la sesión, acceder a partes de acceso restringido, recordar los elementos que integran un pedido, realizar el proceso de compra de un pedido, realizar la solicitud de inscripción o participación en un evento, utilizar elementos de seguridad durante la navegación, almacenar contenidos para la difusión de videos o sonido o compartir contenidos a través de redes sociales.</li><li>Cookies de personalización: Son aquéllas que permiten al usuario acceder al servicio con algunas características de carácter general predefinidas en función de una serie de criterios en el terminal del usuario como por ejemplo serian el idioma, el tipo de navegador a través del cual accede al servicio, la configuración regional desde donde accede al servicio, etc.</li><li>Cookies de análisis: Son aquéllas que bien tratadas por nosotros o por terceros, nos permiten cuantificar el número de usuarios y así realizar la medición y análisis estadístico de la utilización que hacen los usuarios del servicio ofertado. Para ello se analiza su navegación en nuestra página web con el fin de mejorar la oferta de productos o servicios que le ofrecemos.</li><!--<li>Cookies publicitarias: Son aquéllas que, bien tratadas por nosotros o por terceros, nos permiten gestionar de la forma más eficaz posible la oferta de los espacios publicitarios que hay en la página web, adecuando el contenido del anuncio al contenido del servicio solicitado o al uso que realice de nuestra página web. Para ello podemos analizar sus hábitos de navegación en Internet y podemos mostrarle publicidad relacionada con su perfil de navegación.</li><li>Cookies de publicidad comportamental: Son aquéllas que permiten la gestión, de la forma más eficaz posible, de los espacios publicitarios que, en su caso, el editor haya incluido en una página web, aplicación o plataforma desde la que presta el servicio solicitado. Estas cookies almacenan información del comportamiento de los usuarios obtenida a través de la observación continuada de sus hábitos de navegación, lo que permite desarrollar un perfil específico para mostrar publicidad en función del mismo.</li> --></ul>
					<h3>Cookies de terceros</h3>
					<p>La Web de %cliente_web% puede utilizar servicios de terceros que, por cuenta de %cliente_fiscal%, recopilaran información con fines estadísticos, de uso de la página web por parte del usuario y para la prestacion de otros servicios relacionados con la actividad de la página y otros servicios de Internet.</p><p>En particular, este sitio Web utiliza Google Analytics, un servicio analítico de web prestado por Google, Inc. con domicilio en los Estados Unidos con sede central en 1600 Amphitheatre Parkway, Mountain View, California 94043. Para la prestación de estos servicios, se utilizan cookies que recopilan la información, incluida la dirección IP del usuario, que será transmitida, tratada y almacenada por Google en los términos fijados en la Web de Google. Incluyendo la posible transmisión de dicha información a terceros por razones de exigencia legal o cuando dichos terceros procesen la información por cuenta de Google.</p><p>El Usuario acepta expresamente, por la utilización de esta página web, el tratamiento de la información recabada en la forma y con los fines anteriormente mencionados. Y asimismo reconoce conocer la posibilidad de rechazar el tratamiento de tales datos o información rechazando el uso de Cookies mediante la selección de la configuración apropiada a tal fin en su navegador. Si bien esta opción de bloqueo de Cookies en su navegador puede no permitirle el uso pleno de todas las funcionalidades de la página web.</p><p>Puede usted permitir, bloquear o eliminar las cookies instaladas en su equipo mediante la configuración de las opciones del navegador instalado en su ordenador:</p><ul><li><a href="http://support.google.com/chrome/bin/answer.py?hl=es&answer=95647" target="_blank">Chrome</a></li><li><a href="http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9/" target="_blank">Explorer</a></li><li><a href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we" target="_blank">Firefox</a></li><li><a href="http://support.apple.com/kb/ph5042" target="_blank">Safari</a></li></ul><p>Si tiene dudas sobre esta política de cookies, puede contactar con %cliente_fiscal% en %cliente_correo%</p>',
		'eu' => '	<h3>Zer da cookie bat?</h3>
					<p>Zenbait webgunetan sartzean, zure ordenagailuan deskargatzen den fitxategi bat da cookie bat. Cookie-ei esker, webgune batek erabiltzaile baten nabigazio ohiturei buruzko informazioa biltegiratzeko eta berreskuratzeko aukera du, besteak beste. Cookie horiek biltzen duten informazioaren arabera eta tresneria erabiltzen den moduaren arabera, erabiltzailea ezagutzeko erabil daitezke. Erabiltzailearen nabigatzaileak disko gogorrean memorizatzen ditu cookie-ak, baina aribideko saioan soilik, eta, hartara, memorian espazio minimoa okupatzen dute, ordenagailuari kalterik eragin gabe. Cookie-ek ez dute inolako berariazko informazio pertsonalik biltzen, eta gehienak ezabatu egiten dira nabigatzailearen saioa amaitzean (saioko cookie-ak dira).</p><p>Nabigatzaile gehienek estandar gisa onartzen dituzte cookie-ak eta, horiek edozein izanik ere, segurtasun-doikuntzetan ahalbidetu edo eragotzi egiten dituzte aldi baterako edo memorizatutako cookie-ak.</p>
					<h3>Zer cookie mota erabiltzen du web-orri honek?</h3>
					<ul><li>Cookie teknikoak: cookie horiek aukera ematen diote erabiltzaileari web-orri, plataforma edo aplikazio batean nabigatzeko eta bertan dauden zerbitzuak edo aukerak baliatzeko, hala nola datuen trafikoa eta komunikazioa kontrolatzeko, saioa identifikatzeko, sarbide murriztuko aldeetara sartzeko, eskari bat osatzen duten elementuak gogoratzeko, eskari baten erosketa-prozesua egiteko, ekitaldi batean izena emateko edo parte-hartzea eskatzeko, nabigazioan segurtasun-elementuak erabiltzeko, bideoen edo soinuaren difusiorako edukiak biltegiratzeko, edo edukiak sare sozialen bitartez partekatzeko.</li><li>Pertsonalizazioko cookie-ak: cookie horien bitartez, erabiltzailea -dagokion terminalean- hainbat irizpideren arabera aurrez definitutako ezaugarri orokor batzuekin sar daiteke zerbitzura. Ezaugarri horien artean egon daitezke, adibidez, hizkuntza, zerbitzura sartzeko erabili ohi duen nabigatzaile mota, zerbitzura sartzen deneko eskualdeko konfigurazioa, eta abar.</li><li>Azterketako cookie-ak: cookie horiek guk edo hirugarren batzuek ondo tratatuta egonik, erabiltzaile kopurua kuantifikatzeko aukera emango digute, baita eskaintzen den zerbitzuaz erabiltzaileek egiten duten erabileraren neurketa eta analisi estatistikoa egiteko aukera ere. Horretarako, gure web-orrian egin duzun nabigazioa aztertzen da, egiten dugun produktuen edo zerbitzuen eskaintza hobetzearren.</li><!-- --></ul>
					<h3>Hirugarren batzuen cookie-ak</h3>
					<p>%cliente_web% webguneak hirugarren batzuen zerbitzuak balia ditzake, %cliente_fiscal%-(r)en kontura. Informazioa helburu estatistikoarekin bilduko dute, baita erabiltzaileak egiten duen web-orriaren erabileraren helburuarekin, eta orrialdearen jardueraren araberako beste zerbitzu batzuk eta Interneteko beste zerbitzu batzuk egitearen helburuarekin ere.</p><p>Zehazki, webgune honek Google, Inc. konpainiaren Google Analytics zerbitzua erabiltzen du (konpainia horren egoitza zentrala hemen dago: 1600 Amphitheatre Parkway, Mountain View, California 94043, Ameriketako Estatu Batuak). Zerbitzu horiek egiteko, informazioa biltzen duten cookie-ak erabiltzen dira, erabiltzailearen IP helbidea barne. Google-ek bere webgunean ezartzen den moduan igorri, tratatu eta biltegiratuko du informazio hori. Hori dela eta, informazio hori hirugarren batzuei igorri ahal izango die legeak hala eskatzen badu, edo hirugarren batzuek informazio hori Google-en kontura prozesatzen badute.</p><p>Web-orria erabilita, erabiltzaileek espresuki onartzen dute bildutako informazioa aditzera eman den moduan eta adierazitako helburuekin tratatzea. Era berean, onartzen dute datu edo informazio horien tratamendua baztertzeko aukera ezagutzen dutela, cookie-en erabilera baztertuta. Horretarako, nabigatzailean konfigurazio egokia hautatu beharko da. Cookie-ak zure nabigatzailean blokeatzeko aukera horrek ez du web-orriaren funtzionalitate guztiak erabat baliatzea ahalbidetuko.</p><p>Zure tresnerian instalatuta dauden cookie-ak baimendu, blokeatu edo ezaba ditzakezu, zure ordenagailuan instalatuta duzun nabigatzailearen aukeren konfigurazioaren bitartez:</p><ul><li><a href="http://support.google.com/chrome/bin/answer.py?hl=eu&answer=95647" target="_blank">Chrome</a></li><li><a href="http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9/" target="_blank">Explorer</a></li><li><a href="https://support.mozilla.org/eu/kb/enable-and-disable-cookies-website-preferences" target="_blank">Firefox</a></li><li><a href="http://support.apple.com/kb/ph5042" target="_blank">Safari</a></li></ul><p>Cookie-en politika honi buruzko zalantzak badituzu, %cliente_fiscal%-(e)kin harremanetan jar zaitezke honako helbide honetan: %cliente_correo%</p>',
		'en' => '	<h3>What is a cookie?</h3>
					<p>A cookie is a file that is stored on your computer when you visit certain websites. Among other things, cookies enable a website to store and remember information about you or your computer\'s habits and to recognise you, depending on the information they contain and the way you use your computer. Your browser only stores cookies on your hard drive for the duration of your visit; said cookies occupy only minimal memory space and represent no harm to your computer. Cookies contain no specific personal information, and most of them are deleted from your hard drive at the end of your session (these are known as "session cookies").</p><p>Most browsers accept cookies by default. However, you can choose to either accept or block session and persistent cookies in your privacy settings.</p>
					<h3>What kind of cookies is used by this website?</h3>
					<ul><li>Technical cookies: these are cookies that enable you to use a website, platform or application and the different options or services that exist therein. This includes, for example, data traffic and communication control, session identification, access to restricted areas, remembering what\'s in your basket, making purchases of an order, requesting registration or participation in an event, using security elements while browsing, storing contents for the dissemination of video or sound files and sharing content over social networks.</li><li>Functionality cookies: these enable you to access the service with certain general features predefined in your computer, such as language, the type of browser used to access the service, the regional configuration of your place of access, etc.</li><li>Analytical cookies: are cookies which, processed either by us or by third parties, permit us to quantify the number of users and to measure and statistically analyse their use of the service offered. We therefore analyse your use of our website with a view to improving our products and services.</li><!-- --></ul>
					<h3>Third party cookies</h3>
					<p>On its %cliente_web% website, %cliente_fiscal% may request third party services in order to collect statistical information on the use made of our website and to provide other services related to the page activity and other Internet services.</p><p>Particularly, this website uses the Google Analytics service provided by Google, Inc., with its headquarters at 1600 Amphitheatre Parkway, Mountain View, California 94043, USA. Google Analytics uses cookies to generate information, including your IP address, which will be shared, processed and stored by Google in the terms established on the Google website. This includes sharing said information with third parties due to legal requirements or when said third parties process the information for Google.</p><p>By using this website, you expressly agree to us processingthe information obtained in the manner and for the purposes explained above. You also accept that you are aware of theoption to opt-out from said processing of details and information by configuring your browser to block cookies. However, you should note that blocking cookies in your browser may hamper your ability to fully use all of the functions of our website.</p><p>You can accept, block or clear the cookies installed on your computer by configuring the options on your computer browser:</p><ul><li><a href="http://support.google.com/chrome/bin/answer.py?hl=en&answer=95647" target="_blank">Chrome</a></li><li><a href="http://windows.microsoft.com/en-us/windows7/how-to-manage-cookies-in-internet-explorer-9/" target="_blank">Explorer</a></li><li><a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" target="_blank">Firefox</a></li><li><a href="http://support.apple.com/kb/ph5042" target="_blank">Safari</a></li></ul><p>If you have any queries about this cookies policy, you can contact %cliente_fiscal% at %cliente_correo%</p>',
		'fr' => '	<h3>Qu\'est-ce qu\'un cookie?</h3>
					<p>Un cookie est un fichier qui se télécharge sur votre ordinateur lorsque vous accédez à certaines pages d\'un site Internet. Les cookies permettent à un site Internet, entre autres, de stocker et de récupérer des informations sur les habitudes de navigation d\'un utilisateur ou d\'un équipement et, suivant l\'information qu\'ils contiennent et le mode d\'utilisation de votre équipement, ils peuvent être utilisés pour reconnaître l\'utilisateur. Le navigateur de l\'utilisateur mémorise des cookies sur le disque dur uniquement pendant la session en cours et occupe un espace de mémoire minime, sans aucun type de préjudice pour l\'ordinateur. Les cookies ne contiennent aucun type d\'information personnelle spécifique et la plupart d\'entre eux (notamment ceux dénommés "cookies de session") sont éliminés du disque dur à la fin de la session de navigation.</p><p>La plupart des navigateurs acceptent les cookies de manière standard et, en dehors de ces cookies, permettent ou empêchent les cookies temporaires ou mémorisés à travers les réglages de sécurité.</p>
					<h3>Quels sont les types de cookies utilisés par ce site Internet?</h3>
					<ul><li>Cookies techniques: Ce sont ceux qui permettent à l\'utilisateur de naviguer sur le site Internet, plateforme ou application, et d\'utiliser les différentes options ou services qui y sont offerts, comme par exemple, contrôler le trafic et la communication de données, identifier la session, accéder à des sections restreintes, rappeler les données d\'une commande, réaliser le paiement d\'une commande, la demande d\'inscription ou de participation à un événement, utiliser des éléments de sécurité pendant la navigation, stocker des contenus pour la diffusion de fichiers vidéo ou audio, ou partager des contenus à travers des réseaux sociaux.</li><li>Cookies de personnalisation: Ce sont ceux qui permettent à l\'utilisateur d\'accéder au service avec des caractéristiques de caractère général prédéfinies en fonction d\'une série de critères sur le terminal de l\'utilisateur, comme par exemple la langue, le type de navigateur à travers lequel ce dernier accède au service, la configuration régionale depuis laquelle il accède au service, etc.</li><li>Cookies d\'analyse: Ce sont ceux qui sont, soit traités par nous, soit par des tiers, et qui permettent de quantifier le nombre d\'utilisateurs et donc de réaliser la mesure et l\'analyse statistique de l\'utilisation de notre service par les utilisateurs. Pour cela, nous analysons leur navigation sur notre site Internet, afin d\'améliorer nos prestations, en produits et en services.</li><!-- --></ul>
					<h3>Cookies de tiers</h3>
					<p>Le site Internet %cliente_web% susceptible d\'utiliser des services de tiers qui, pour le compte de %cliente_fiscal%, recueilleront des informations à des fins statistiques sur l\'utilisation du site par l\'utilisateur et pour la prestation d\'autres services en rapport avec l\'activité du site et autres services d\'Internet.</p><p>Ce site Internet fait notamment appel à Google Analytics, un service d\'analyse de sites Internet prêté par Google, Inc. dont le domicile est établi aux États-Unis et le siège central à 1600 Amphitheatre Parkway, Mountain View, California 94043. Pour la prestation de ces services, des cookies sont utilisés pour la collecte d\'information, y compris l\'adresse IP de l\'utilisateur, qui sera transmise, traitée et stockée par Google dans les termes fixés sur le site Internet de Google. Ceci inclut l\'éventuelle transmission de cette information à des tiers pour des raisons d\'ordre légal ou dans le cas où ces tiers travaillent pour le compte de Google</p><p>En utilisant ce site Internet, l\'utilisateur accepte expressément le traitement de l\'information recueillie sous la forme et aux fins mentionnées précédemment. Il admet aussi connaître la possibilité qui lui est offerte de refuser le traitement de ces données ou information en bloquant l\'utilisation des Cookies dans la configuration de son navigateur. Cette option de blocage des Cookies sur son navigateur pourrait toutefois restreindre les fonctionnalités de son accès au site Internet.</p><p>L\'utilisateur peut autoriser, bloquer ou éliminer les cookies installés sur son équipement en configurant les options du navigateur installé sur son ordinateur:</p><ul><li><a href="http://support.google.com/chrome/bin/answer.py?hl=fr&answer=95647" target="_blank">Chrome</a></li><li><a href="http://windows.microsoft.com/fr-fr/windows7/how-to-manage-cookies-in-internet-explorer-9/" target="_blank">Explorer</a></li><li><a href="https://support.mozilla.org/fr/kb/activer-desactiver-cookies" target="_blank">Firefox</a></li><li><a href="http://support.apple.com/kb/ph5042" target="_blank">Safari</a></li></ul><p>En cas de doutes sur cette politique de cookies, vous pouvez contacter %cliente_fiscal% en écrivant à %cliente_correo%</p>',
		'de' => '	<h3>Was ist ein Cookie?</h3>
					<p>Cookies sind Dateien, die beim Zugriff auf bestimmte Webseiten in Ihren Computer heruntergeladen werden. Unter anderem ermöglichen die Cookies einer Website, Informationen über die Surfgewohnheiten eines Benutzers oder seinen Computer zu speichern oder wiederherzustellen und, abhängig von den Informationen, die sie enthalten und wie Sie Ihren Computer nutzen, können sie verwendet werden, um den Benutzer zu erkennen.Der Browser des Benutzers speichert Cookies nur während der aktuellen Sitzung auf der Festplatte, wobei sie nur sehr wenig Speicherplatz einnehmen und Ihren Computer nicht schädigen.Die Cookies enthalten keine personenspezifischen Informationen und die meisten werden am Ende der Browser-Sitzung (sog. Session-Cookies) von der Festplatte gelöscht.</p><p>Die meisten Browser akzeptieren Cookies standardmäßig und erlauben oder unterbinden unabhängig hiervon temporäre oder gespeicherte Cookies in den Sicherheitseinstellungen.</p>
					<h3>Welche Arten von Cookies verwendet diese Website?</h3>
					<ul><li>Technische Cookies: Dies sind jene Cookies, die dem Benutzer erlauben, auf einer Webseite, Plattform oder Anwendung zu browsen sowie die hierin enthaltenen verschiedenen Optionen oder Dienstleistungen zu nutzen, wie zum Beispiel den Datenverkehr und die Datenkommunikation zu kontrollieren, die Sitzung zu identifizieren, den Zugang zu Bereichen mit beschränktem Zugang zu erstellen, Elemente einer Bestellung zu speichern, einen Kaufvorgang durchzuführen, einen Antrag auf Anmeldung zu stellen oder die Teilnahme an einer Veranstaltung, während des Surfens Sicherheitsfunktionen zu verwenden, Inhalte zur Wiedergabe von Videos oder Tonaufnahmen zu speichern oder diese über die sozialen Netzwerke zu teilen.</li><li>Personalisierungs-Cookies: Dies sind jene Cookies, die es dem Benutzer gestatten, im Endgerät des Benutzers gemäß bestimmter Kriterien auf zuvor definierte Merkmale allgemeiner Art zuzugreifen wie zum Beispiel die Sprache, die Art des Browsers, über dender Benutzer auf die Serviceleistung zugreift, die regionale Konfiguration, von der er auf die Serviceleistung zugreift etc.</li><li>Analyse-Cookies: Dies sind jene Cookies, die bei guter Auswertung durch uns oder Drittanbieter erlauben, die Zahl der Benutzer zu quantifizieren und  eine Messung und statistische Analyse der Nutzung der bereitgestellten Dienste durch die Benutzer der Serviceleistung durchzuführen.Hierzu analysieren wir Ihr Surfverhalten auf unserer Webseite, mit dem Ziel, unser Produkt- und Serviceangebot zu verbessern.</li></ul>
					<h3>Cookies von Drittanbietern</h3>
					<p>Die Website von %cliente_web% kann Fremdleistungen von Drittanbietern nutzen, welche im Namen von %cliente_fiscal% zu statistischen Zwecken Informationen zur Nutzung der Website durch den Benutzer und zur Erbringung weiterer, mit der Aktivität der Webseite und sonstigen Internetdiensten in Zusammenhang stehenden Informationensammeln.</p><p>Diese Website benutzt vor allem Google Analytics, einen Webanalysedienst der Google Inc., mit Sitz in den Vereinigten Staaten in 1600 Amphitheatre Parkway, Mountain View, California 94043. Zur Erbringung dieser Dienstleistungen werden Cookies eingesetzt, welche Informationen, einschließlich der IP-Adresse des Nutzers sammeln und sie gemäß den in der Website von Google festgelegten Bedingungen durch Google übertragen, verarbeiten und speichern. Einschließlich der möglichen Übertragung dieser Informationen an Dritte aus rechtlichen Gründen oder wenn diese Dritten die Daten im Auftrag von Google bearbeiten.</p><p>Der Benutzer stimmt durch die Nutzung dieser Website der Verarbeitung der in der oben genannten Weise und zum angeführten Zweck gesammelten Informationausdrücklich zu.Zudem räumt er die Möglichkeit der Ablehnung der Verarbeitung dieser Daten und Informationen ein durch die Ablehnung der Verwendung von Cookies, indem er in seinem Browser die entsprechende Einstellung konfiguriert.Jedoch kann die Option der Sperrung von Cookies in Ihrem Browser zur Folge haben, dass er möglicherweise nicht alle Funktionen der Webseite voll nutzen kann.</p><p>Sie können die auf Ihrem Computer installierten Cookies zulassen, blockieren oder löschen mittels der auf Ihrem Computer installierten Browser-Optionen:</p><ul><li><a href="http://support.google.com/chrome/bin/answer.py?hl=de&answer=95647" target="_blank">Chrome</a></li><li><a href="http://windows.microsoft.com/de-de/windows7/how-to-manage-cookies-in-internet-explorer-9/" target="_blank">Explorer</a></li><li><a href="https://support.mozilla.org/de/kb/cookies-erlauben-und-ablehnen" target="_blank">Firefox</a></li><li><a href="http://support.apple.com/kb/ph5042" target="_blank">Safari</a></li></ul><p>Wenn Sie Fragen zu dieser Cookies-Politik haben, können Sie sich unter %cliente_correo% mit %cliente_fiscal% in Verbindung setzen.</p>',
	),
	'Política de cookies (faldón)' => array(
		'es' => 	'Utilizamos cookies propias y de terceros para mejorar nuestros servicios mediante el análisis de sus hábitos de navegación. Si continua navegando, consideramos que acepta su uso. Puede obtener más información pulsando en [este enlace]',
		'eu' => 	'Gure cookie-ak eta hirugarren batzuenak erabiltzen ditugu zure nabigazio-ohiturak aztertu eta, hala, gure zerbitzuak hobetzeko. Nabigatzen jarraitzen baduzu, cookie horiek erabiltzea onartzen duzula ulertuko dugu. Informazio gehiago lor dezakezu [esteka honetan] sakatuta.',
		'en' => 	'We use our own and third party cookies to improve our services by analysing your online movements. If you stay on this page, we will consider that you accept their use. You can obtain more information by clicking on [this link].',
		'fr' => 	'Nous utilisons nos propres cookies et des cookies de tiers pour améliorer nos services grâce à l\'analyse de vos habitudes de navigation. Si vous poursuivez votre navigation, nous considérerons que vous acceptez leur utilisation. Vous pouvez obtenir davantage d\'information en cliquant sur [ce lien].',
		'de' => 	'Wir verwenden eigene und Cookies von Drittanbietern, um unsere Serviceleistungen anhand der Analyse Ihrer Surfgewohnheiten zu verbessern.Wenn Sie weiterhin auf dieser Website browsen, gehen wir davon aus, dass Sie ihre Verwendung akzeptieren. Sie können die weitere Informationen erhalten, indem Sie [diesen Link] anklicken.',
	),
);


/*** Formulario ***/
?>

<style type="text/css">div{margin:0 0 5px 0;}input{width:200px;}fieldset{font-family:Calibri;}legend{font-size:25px;font-weight:bold;}</style>

<form action="" method="post">
	<fieldset id="cliente">
		<legend>Cliente</legend>
		<div>
			<input type="text" name="cliente_nombre" placeholder="Nombre comercial" required maxlength="100" value="<?php echo ((isset($_POST['cliente_nombre'])==true) ? $_POST['cliente_nombre'] : '');?>" />
			<input type="text" name="cliente_fiscal" placeholder="Nombre fiscal" required maxlength="100" value="<?php echo ((isset($_POST['cliente_fiscal'])==true) ? $_POST['cliente_fiscal'] : '');?>" />
			<input type="text" name="cliente_nif" placeholder="NIF" required maxlength="15" value="<?php echo ((isset($_POST['cliente_nif'])==true) ? $_POST['cliente_nif'] : '');?>" />
		</div>
		<div>
			<input type="text" name="cliente_direccion_1" placeholder="Calle, paseo, ..." required maxlength="100" value="<?php echo ((isset($_POST['cliente_direccion_1'])==true) ? $_POST['cliente_direccion_1'] : '');?>" />
			<input type="text" name="cliente_direccion_2" placeholder="CP, ciudad, provincia" required maxlength="100" value="<?php echo ((isset($_POST['cliente_direccion_2'])==true) ? $_POST['cliente_direccion_2'] : '');?>" />
			<input type="text" name="cliente_telefono" placeholder="Teléfono" required maxlength="20" value="<?php echo ((isset($_POST['cliente_telefono'])==true) ? $_POST['cliente_telefono'] : '');?>" />
		</div>
		<div>
			<input type="text" name="cliente_dominio" placeholder="Dominio" required maxlength="100" value="<?php echo ((isset($_POST['cliente_dominio'])==true) ? $_POST['cliente_dominio'] : '');?>" />
			<input type="text" name="cliente_correo" placeholder="Email" required maxlength="100" value="<?php echo ((isset($_POST['cliente_correo'])==true) ? $_POST['cliente_correo'] : '');?>" />
			<input type="text" name="cliente_correo_pd" placeholder="Email (protección de datos)" required maxlength="100" value="<?php echo ((isset($_POST['cliente_correo_pd'])==true) ? $_POST['cliente_correo_pd'] : '');?>" />
		</div>
		<div>
			<input type="text" name="cliente_rm_ubicacion" placeholder="RM (Provincia)" maxlength="50" value="<?php echo ((isset($_POST['cliente_rm_ubicacion'])==true) ? $_POST['cliente_rm_ubicacion'] : '');?>" />
			<input type="text" name="cliente_rm_inscripcion" placeholder="RM (Tomo N, Libro N, Folio N, Sección N, Hoja LN, Inscripción N)" maxlength="200" value="<?php echo ((isset($_POST['cliente_rm_inscripcion'])==true) ? $_POST['cliente_rm_inscripcion'] : '');?>" />
		</div>
		<div>
			<button type="submit">Generar textos personalizados</button>
		</div>
	</fieldset>
</form>

<?php
/*** Textos personalizados ***/
if (sizeof($_POST)>0) {
	foreach ($array_textos AS $str_tipo => $array_textos_idiomas) {?>
<fieldset>
	<legend>Tipo: <?php echo $str_tipo;?></legend>
<?php	foreach ($array_textos_idiomas AS $str_idioma => $str_texto) {
			// Datos básicos
			$str_texto = str_replace(
				array('%cliente_nombre%','%cliente_fiscal%','%cliente_nif%','%cliente_rm_ubicacion%','%cliente_rm_inscripcion%','%cliente_direccion_1%','%cliente_direccion_2%','%cliente_telefono%','%cliente_correo%','%cliente_correo_pd%','%cliente_web%'),
				array($_POST['cliente_nombre'],$_POST['cliente_fiscal'],$_POST['cliente_nif'],$_POST['cliente_rm_ubicacion'],$_POST['cliente_rm_inscripcion'],$_POST['cliente_direccion_1'],$_POST['cliente_direccion_2'],$_POST['cliente_telefono'],$_POST['cliente_correo'],$_POST['cliente_correo_pd'],$_POST['cliente_dominio']),
				$str_texto
			);
			// Registro mercantil (opcional)
			if ($_POST['cliente_rm_inscripcion']=='' OR $_POST['cliente_rm_ubicacion']=='') {
				$str_texto = preg_replace('/%registro_mercantil%.+%\/registro_mercantil%/', '', $str_texto);
			} else {
				$str_texto = preg_replace('/(%registro_mercantil%|%\/registro_mercantil%)/', '', $str_texto);
			}?>
	<fieldset>
		<legend>Idioma: <?php echo $str_idioma;?></legend>
		<fieldset>
			<legend>Formato: Código</legend>
			<?php echo htmlentities($str_texto, ENT_QUOTES);?>
		</fieldset>
<?php 		if (strip_tags($str_texto, ENT_QUOTES)!=$str_texto) {?>
		<fieldset>
			<legend>Formato: HTML</legend>
			<?php echo $str_texto;?>
		</fieldset>
<?php 		}?>
	</fieldset>
<?php	}?>
</fieldset>
<?php }
}
?>